{% set version = "2.0" %}
{% set sha256 = "3ec0795f2776e69e4c8a35a34ddd199d0ee2119a2e65a3a944374e52edb06b26" %}

package:
  name: lcov
  version: {{ version }}

source:
  url: https://github.com/linux-test-project/lcov/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - 0001-Run-updateversion.pl-directly-without-env-for-Windows.patch

build:
  number: 0

requirements:
  build:
    - perl 5.*
    - make
    - m2-bash       # [win]
    - m2-coreutils  # [win]
  host:
  run:
    - perl 5.*

test:
  commands:
    - lcov --version | grep -qF '{{ version }}'    # [unix]
    - lcov --version | findstr "/C:{{ version }}"  # [win]

about:
  home: http://ltp.sourceforge.net/test/coverage/lcov.php
  summary: LCOV is an extension of GCOV, a GNU tool which provides information about what parts of a program are actually executed (i.e. "covered") while running a particular test case.
  license: GPL-2.0-or-later
  license_family: GPL-2
  license_url: https://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html
  license_file: COPYING

extra:
  recipe-maintainers:
    - mjscosta
    - MuellerSeb
    - wolfv
