{% set version = "1.15" %}
{% set sha256 = "d88b0718f59815862785ac379aed56974b9edd8037567347ae70081cd4a3542a" %}

package:
  name: lcov
  version: {{ version }}

source:
  url: https://github.com/linux-test-project/lcov/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1

requirements:
  build:
    - perl 5.*
    - make
  host:
  run:
    - perl 5.*

test:
  commands:
    - lcov --version | grep -qF '{{ version }}'    # [unix]
    - lcov --version | findstr "/C:{{ version }}"  # [win]

about:
  home: http://ltp.sourceforge.net/test/coverage/lcov.php
  summary: LCOV is an extension of GCOV, a GNU tool which provides information about what parts of a program are actually executed (i.e. "covered") while running a particular test case.
  license: GPL-2.0-or-later
  license_family: GPL-2
  license_url: https://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html
  license_file: COPYING

extra:
  recipe-maintainers:
    - mjscosta
