appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: skN5YlRHQkZUAB0vpXDPi2dyFsAqSeU18pSiuR3VhBbnLZsULmY9Y9CHn6tdcHJbIpeWyFfrzEa8WrzgpNQB0rq3F1Ru8Qe8egIIc9BAel8cuyRCdFdPxEi6l0zIRCLZ4HvzDpoLuppxqWWR/uNkSMJOxiPbi/w6LHEjyVE0KPcIlRyhe3iAlgyHHRWSuAZG7N0fCxZlTZDDNyWna5wId1C8hVA8kV5kaBAaVFbuoLG7hP2cDpwrDnPMsZKAPPllCSOeJkfSNGKdzHVjW/lIeoDZPP+pqTpJumjIfb1iw05gq+mKD4q5AeJgj8GosCIzek5bBTSTzfwHbZDyIZxYY3WYSozEh5DtfO//9gnsbtmdjYhXPcxt+YAWEm/1dipXCEaTj3mfjQaMHjMN1+yXCgrlTfMXXiTZbgE2Dc4OBdfi8qfqcngL+T/v7fVSjAZZ08pEOTZ0sRU18KXMlPrbMvzIO/cmCHNnNf+q4O58SV2qeM15ilq0caTxT2+WcApO8XwbiNoe6RboEYL7Yot039kYpFJKo6+88MTvLGs0fwIdTiTnRqABieeSwyZEm7xTXps8IuwMr2YU49LsVStSmMCntdjjYR6Ca+z4Q5+lBELZa4u2XSh+Vd91gPvNWlPch4dDhxUGrX3R0mtJzYanqGAAeB6PgdSoDta4ifQutxo=}
